### ISSUE TITLE
Move/contribute into scala-steward-org

### ISSUE THREAD

**Issue by MPV** [scala-steward-org/charts#3]
Would you be open to moving/contributing this into the Scala Steward organisation on GitHub?

https://github.com/scala-steward-org/

**Comment by MPV** [comment]
@fthomas: what's your view (on moving this into [scala-steward-org](https://github.com/scala-steward-org/))?

**Comment by MaT1g3R** [comment]
@MPV I would be open to move this over to Scala Steward org, @jsoref thoughts?

**Comment by jsoref** [comment]
I'm fine w/ moving it.

**Comment by MPV** [comment]
Cool!

I've asked the equivalent question over in https://github.com/fthomas/scala-steward/issues/518#issuecomment-642646007 too. 😊

**Comment by fthomas** [comment]
I'm open to having this under the scala-steward-org organization if it useful for other people that use Kubernetes and Helm.

**Comment by MPV** [comment]
How might we do this? 
What could next steps be?

**Comment by fthomas** [comment]
I need to invite someone to the scala-steward-org who has admin permissions here to move the repository. Who should I invite?

**Comment by vmandrychenko** [comment]
Please invite @jsoref

**Comment by fthomas** [comment]
I've invited @jsoref.

**Comment by jsoref** [comment]
> Moving repository to scala-steward-org/charts. This may take a few minutes.

**Comment by jsoref** [comment]
Hmm, it's moved. Now I can't seem to resolve this issue...
@fthomas are the org permissions odd?

**Comment by fthomas** [comment]
I just assigned you the `Maintain` role in this repository, @jsoref. You should be able to close this now.

**Comment by MPV** [comment]
Nice! 😍

Should we change some code to rename helm repo etc (either before closing this issue, or another one)? 😊

**Comment by jsoref** [comment]
We should definitely make some changes, updating things to reference the new org path at least.

**Comment by MPV** [comment]
Nice! I was thinking about making a PR, but didn't know what to fill in everywhere, for example maintainer email for the chart:

https://github.com/scala-steward-org/charts/blob/master/charts/scala-steward/Chart.yaml#L16

Or would we keep that for now?

**Comment by MaT1g3R** [comment]
We could keep it for now until we find a new maintainer. We (garner) will still be maintaining in either way since we actively use it.

**Comment by MPV** [comment]
Any further changes, or could we close this one for now?

**Comment by jsoref** [comment]
We can close
