### ISSUE TITLE
Can't download charts, outdated links in gh-pages index.yaml

### ISSUE THREAD

**Issue by hgranillo** [scala-steward-org/charts#6]
Hi all, it seems that the index of the helm chart repository has links to the now deprecated GarnerCorp repo, making it not possible to download the chart from https://github.com/scala-steward-org/charts 

For example:
https://github.com/scala-steward-org/charts/blob/b20a8786176911ed6b03309ae7596ad74ec10a01/index.yaml#L23

How to reproduce:
```
❯ helm repo add scala-steward-org https://scala-steward-org.github.io/charts
"scala-steward-org" has been added to your repositories
❯ helm repo update
Hang tight while we grab the latest from your chart repositories...
❯ helm pull scala-steward-org/scala-steward
Error: failed to fetch https://github.com/GarnerCorp/charts/releases/download/scala-steward-0.2.2/scala-steward-0.2.2.tgz : 404 Not Found
```

**Comment by jsoref** [comment]
Sorry about that. Fixed by #7
